### ISSUE TITLE
Create a way to Access the different use cases on Zephyr

### ISSUE THREAD

**Issue by BBland1999** [segFaultCity/ZephyrGroup3#14]
Solution: create a switch case that leads to the logic for each use case's logic.

**Comment by segFaultCity** [comment]
Almost finished, but the app crashes unexpectedly when trying to run for daily schedules. No error spotted within any .c file. The problem must reside in the PHP web service. New contributors to this issue should focus on the web side.

**Comment by BBland1999** [comment]
There is now a way to select the use cases by answering a prompt.
