### ISSUE TITLE
Grab daily reminders via HTTP (Zephyr App)

### ISSUE THREAD

**Issue by segFaultCity** [segFaultCity/ZephyrGroup3#7]
Problem:
Zephyr app does not currently implement the daily reminders use case.
Solution:
Refer to infant routine mode for the zephyr app and use that structure to create the daily reminders implementation.

This issue should be closed when the Zephyr application can successfully use GET request to grab alarm information from the web service and display it.

**Comment by BBland1999** [comment]
The user is now able to select the correct use case by answering a prompt.
