### ISSUE TITLE
Grab random reminders via HTTP (Zephyr App)

### ISSUE THREAD

**Issue by segFaultCity** [segFaultCity/ZephyrGroup3#9]
This issue should be closed when the Zephyr application can successfully grab and display user random reminder information on our web service using a GET request.

**Comment by BBland1999** [comment]
The problem should be able to be solved by modifying the request that was used for the infant reminders routine.

**Comment by BBland1999** [comment]
This can now be selected by answering the prompt in the zephyr app.
